anjo/blog/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('anjo.blog.views',
	url(r'^posts/$', 'list_posts', name='listposts'),
	url(r'^ler-post-completo/(?P<id>\d+)/$', 'post_details', name='postdetails'),
)

anjo/campaign/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('anjo.campaign.views',
	url(r'^criar-campanha/$', 'create_campaign', name='createcampaign'),
	url(r'^lista-de-campanhas/$', 'list_campaign', name='listcampaign'),
	url(r'^detalhes-da-campanha/(?P<id>\d+)/$', 'details', name='campaigndetails'),
	url(r'^minhas-campanhas/(?P<user_id>\d+)/$', 'list_my_campaign', name='mylistcampaign'),
	url(r'^recebido-campanha/(?P<campaign_id>\d+)/$', 'received', name='receivedcampaign'),
	url(r'^solicitar-saque/$', 'get_payment', name='getpayment'),
	url(r'^sucesso/$', 'create_campaign', name='succ'),
)

anjo/core/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('anjo.core.views',
	url(r'^$', 'homepage', name='homepage'),
	url(r'^enviar-depoimento/$', 'create_testimonial', name='createtestimonial'),
	url(r'^depoimentos/$', 'testimonial', name='testimonials'),
	url(r'^dados-bancarios/$', 'add_bank', name='addbank'),
	url(r'^quem-somos/$', 'about', name='aboutus'),
	url(r'^como-funciona/$', 'howitwork', name='howwork'),
	url(r'^anjos/$', 'donor', name='donors'),
	url(r'^novo-usuario/$', 'register', name='newuser'),
	url(r'^login/$', 'user_login', name='userlogin'),
	url(r'^usuario-logado/$', 'user_logged', name='userlogged'),
	url(r'^logout/$', 'user_logout', name='userlogout'),
	url(r'^meus-dados/(?P<user_id>\d+)/$', 'user_information', name='userinfor'),
)

anjo/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^campanha/', include('anjo.campaign.urls', namespace='campaign')),
    url(r'^blog/', include('anjo.blog.urls', namespace='blog')),
    # Examples:
    # url(r'^$', 'anjo.views.home', name='home'),
    # url(r'^anjo/', include('anjo.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('anjo.core.urls', namespace='home')),
)

from django.conf import settings
urlpatterns += patterns('django.views.static',
	url(r'^static/(?P<path>.*)$', 'serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', 'serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^js/(?P<path>.*)$', 'serve', {'document_root': 'public/js'}),
)

anjo/core/models.py
#coding: utf-8
from django.db import models
from django.contrib.auth.models import User
from anjo.campaign.models import Campaign

# Create your models here.
class AboutUs(models.Model):
	title = models.CharField(max_length=70)
	about_us = models.TextField()

	def __unicode__(self):
		return self.title

	class Meta:
		verbose_name=u'About Us'
		verbose_name_plural=u'About Us'

class HowItWork(models.Model):
	title = models.CharField(max_length=70)
	how_work = models.TextField()

	def __unicode__(self):
		return self.title

	class Meta:
		verbose_name=u'How it Work'
		verbose_name_plural=u'How it Work'

class UserProfile(models.Model):
	GENDER_CHOICES = (
		('M', 'Masculino'),
		('F', 'Feminino')
	)
	user = models.OneToOneField(User)
	cpf = models.CharField(u'CPF', max_length=14, help_text='Formato: 000.000.000-00')
	birthday = models.DateField(u'Data de Nascimento', help_text='Formato: 00/00/0000')
	gender = models.CharField(u'Sexo', max_length=1, choices=GENDER_CHOICES)
	address = models.CharField(u'Endereço', max_length=100, help_text='Informe seu endereço completo')
	code_postal = models.CharField(u'CEP', max_length=10, help_text='Formato: 00.000-000')
	neighborhood = models.CharField(u'Bairro', max_length=50)
	state = models.CharField(u'Estado', max_length=2)
	city = models.CharField(u'Cidade', max_length=50)
	phone_number = models.CharField(u'Telefone/Celular', max_length=14, help_text='Formato: (00)00000-0000')
	created_at = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.user.username

class Testimonials(models.Model):
	name = models.CharField(u'Nome', max_length=30)
	message = models.TextField(u'Mensagem')
	active = models.BooleanField(default=False)
	created_at = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.name

class Banks(models.Model):
	code_bank = models.PositiveIntegerField(u'Número do Banco', blank=True, null=True)
	bank_name = models.CharField(u'Nome do Banco', max_length=70)

	def __unicode__(self):
		return self.bank_name

	class Meta:
		verbose_name=u'Bank'
		verbose_name_plural=u'Banks'

class UserBank(models.Model):
	user = models.ForeignKey(User, blank=True, null=True, verbose_name=u'Usuário')
	bank = models.ForeignKey('Banks', verbose_name=u'Banco', unique=True)
	agency = models.CharField(u'Agência', max_length=20, unique=True)
	account_bank = models.CharField(u'Conta Bancária', max_length=50, unique=True)
	operation = models.CharField(u'Operação', max_length=10, blank=True, null=True, unique=True, help_text='Para correntista da CEF')

	def __unicode__(self):
		return "%s, %s, %s" % (self.bank, self.agency, self.account_bank)

	class Meta:
		verbose_name=u'User Bank'
		verbose_name_plural=u'User\'s Bank'

class DashUser(models.Model):
	campaign = models.ForeignKey(Campaign)
	name_donator = models.CharField(max_length=100, blank=True)
	email_donator = models.EmailField(blank=True)
	value = models.DecimalField(max_digits=15, decimal_places=2)

	def __unicode__(self):
		return "%s - %s - %d" % (self.name_donator, self.email_donator, self.value)

anjo/core/forms.py
#coding: utf-8
from django import forms
from localflavor.br.br_states import STATE_CHOICES
from django.contrib.auth.models import User
from .models import UserProfile, Testimonials, UserBank, Banks


class TestimonialsForm(forms.ModelForm):
	class Meta:
		model = Testimonials
		exclude = ('active',)

class UserForm(forms.ModelForm):
	first_name = forms.CharField(label='Nome')
	last_name = forms.CharField(label='Sobrenome')
	username = forms.CharField(label='Nome de usuário')
	email = forms.EmailField(label='E-mail')
	password = forms.CharField(label='Senha', widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
	state = forms.ChoiceField(label='Estado', choices=STATE_CHOICES)

	class Meta:
		model = UserProfile
		fields = ('cpf', 'birthday', 'gender', 'address', 'code_postal', 'neighborhood', 'state', 'city', 'phone_number')

class BanksForm(forms.ModelForm):
	class Meta:
		model = Banks
		excludes = ('code_bank')

class UserBankForm(forms.ModelForm):
	class Meta:
		model = UserBank
		excludes = ('user')

anjo/core/views.py
# coding: utf-8
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect

from .models import UserProfile, UserBank

from .models import AboutUs, HowItWork, Testimonials
from anjo.campaign.models import Campaign
from anjo.blog.models import Post
from .forms import UserForm, UserProfileForm, TestimonialsForm, UserBankForm, BanksForm

def homepage(request):
	campaign = Campaign.objects.all().order_by('-created_at')[:5]
	camp_created = Campaign.objects.all().order_by('-created_at')[:4]
	return render(request, 'index.html', {'campaign': campaign, 'camp_created': camp_created})

def about(request):
	about_us = AboutUs.objects.all()
	return render(request, 'core/about_us.html', {'about_us': about_us})

def howitwork(request):
	how_work = HowItWork.objects.all()
	return render(request, 'core/how_it_work.html', {'how_work': how_work})

def donor(request):
	return render(request, 'core/donors.html')

def register(request):

	registered = False

	if request.method == 'POST':
		user_form = UserForm(data=request.POST)
		profile_form = UserProfileForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():

			user = user_form.save()

			user.set_password(user.password)
			user.save()

			profile = profile_form.save(commit=False)
			profile.user = user

			profile.save()

			registered = True

		else:
			print user_form.errors, profile_form.errors
	
	else:
		user_form = UserForm()
		profile_form = UserProfileForm()

	return render(request, 'core/register_user.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):

	if request.method == 'POST':

		username = request.POST['username']
		password = request.POST['password']

		user = authenticate(username=username, password=password)

		if user is not None:

			if user.is_active:
				login(request, user)
				return HttpResponseRedirect('/usuario-logado/')
			else:
				return HttpResponse('Sua conta está desabilitada.')
		else:
			print('Login inválido, detalhes: {0}, {1}'.format(username, password))
			login_error = 'Ops! Alguma coisa que "não está certo" deu errado! Por favor, tente novamente. :)'
			return render(request, 'core/user_login.html', {'login_error': login_error})

	else:
		return render(request, 'core/user_login.html', {})

@login_required
def user_logged(request):
	return render(request, 'core/user_logged.html')

@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect('/')

def create_testimonial(request):
	created = False
	
	if request.method == 'POST':
		test_form = TestimonialsForm(data=request.POST)
		if test_form.is_valid():
			test_form.save()
			created = True
	else:
		test_form = TestimonialsForm()
	return render(request, 'core/create_testimonial.html', {'test_form': test_form, 'created': created})



def testimonial(request):
	testimonial = Testimonials.objects.all().order_by('-created_at')
	return render(request, 'core/testimonials.html', {'testimonial': testimonial})


@login_required
def add_bank(request):
	created = False
	if request.method == 'POST':
		bank_form = UserBankForm(request.POST)
		if bank_form.is_valid():
			bf = bank_form.save(commit=False)
			bf.user = request.user
			bf.save()
			created = True
		else:
			print(bank_form.errors)
	else:
		bank_form = UserBankForm()
	return render(request, 'core/user_bank.html', {'bank_form': bank_form, 'created': created})

@login_required
def user_information(request, user_id):
	user_infor = get_object_or_404(UserProfile, user=user_id)
	user_bank = get_object_or_404(UserBank, user=user_id)
	return render(request, 'core/user_information.html', {'user_infor': user_infor, 'user_bank': user_bank})

anjo/core/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-BR">
    <head>
        <title>{% block title %}Anjo Meu - Doar faz bem!{% endblock title %}</title>
        <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,800" rel="stylesheet" type="text/css" />
        <link href="http://fonts.googleapis.com/css?family=Oleo+Script:400" rel="stylesheet" type="text/css" />
        <script src="{{ STATIC_URL }}js/jquery.min.js"></script>
        <script src="{{ STATIC_URL }}js/jquery.maskedinput.min.js"></script>
        <script src="{{ STATIC_URL }}js/jquery.maskMoney.min.js"></script>
        <script src="{{ STATIC_URL }}js/mask.js"></script>
        <script src="{{ STATIC_URL }}js/config.js"></script>
        <script src="{{ STATIC_URL }}js/skel.min.js"></script>
        <script src="{{ STATIC_URL }}js/skel-panels.min.js"></script>
        <link rel="stylesheet" href="{{ STATIC_URL }}css/normalize.css" />
        <link rel="stylesheet" href="{{ STATIC_URL }}css/form.css" />
        <link rel="stylesheet" href="{{ STATIC_URL }}css/skel-noscript.css" />
        <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css" />
        <link rel="stylesheet" href="{{ STATIC_URL }}css/style-desktop.css" />
        <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.css" />
        <!--[if lte IE 8]><script src="{{ STATIC_URL }}js/html5shiv.js"></script><link rel="stylesheet" href="{{ STATIC_URL }}css/ie8.css" /><![endif]-->
        <!--[if lte IE 7]><link rel="stylesheet" href="{{ STATIC_URL }}css/ie7.css" /><![endif]-->
    </head>
    <body class="homepage">
    <!-- Facebook SDK -->
    <div id="fb-root"></div>
    <script>
        (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=450803851719266";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>

        <section class="link-top">
            <nav>
                <ul>
                    {% if not user.is_authenticated %}
                        <li><a href="{% url 'home:userlogin' %}">Login</a></li>
                    {% else %}
                        <li>Seja bem-vindo {{ user.first_name }}!</li>
                        <li><a href="{% url 'home:userlogged' %}">Acessar painel</a></li>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'home:userlogout' %}">Sair</li></a>
                    {% endif %}
                </ul>
            </nav>
        </section>

        <!-- Header Wrapper -->
            <div id="header-wrapper">
                <div class="container">
                    <div class="row">
                        <div class="12u">
                        
                            <!-- Header -->
                                <header id="header">
                                
                                    <!-- Logo -->
                                        <div id="logo">
                                            <h1><a href="{% url 'home:homepage' %}" id="logo"><img src="{{ STATIC_URL }}images/Marca_Azul.png"></a></h1>
                                        </div>
                                        <section class="slogan">
                                            <p>Doar faz bem!</p>
                                        </section>
                                    
                                    <!-- Nav -->
                                        <nav id="nav">
                                            <ul>
                                                <li class="current_page_item"><a href="{% url 'home:homepage' %}">Home</a></li>
                                                <li><a href="{% url 'home:aboutus' %}">Quem somos</a></li>
                                                <li><a href="{% url 'home:howwork' %}">Como funciona</a></li>
                                                <li><a href="{% url 'home:donors' %}">Anjos</a></li>
                                                <li><a href="{% url 'home:testimonials' %}">Depoimentos</a></li>
                                            </ul>
                                        </nav>
                                
                                </header>

                        </div>
                    </div>
                </div>
            </div>
        
        <!-- Banner Wrapper -->
            {% block content %}

            {% endblock content %}

        <!-- Footer Wrapper -->
            <div id="footer-wrapper">
                <footer id="footer" class="container">
                    <div class="row">
                        <div class="3u">
                        
                            <!-- Links -->
                                <section class="widget-links">
                                   <h2>Acessos</h2>
                                    <ul class="style2">
                                        <li><a href="{% url 'home:homepage' %}">Home</a></li>
                                        <li><a href="{% url 'home:aboutus' %}">Quem somos</a></li>
                                        <li><a href="{% url 'home:howwork' %}">Como funciona</a></li>
                                        <li><a href="{% url 'home:donors' %}">Doadores</a></li>
                                    </ul>
                                </section>
                        
                        </div>
                        <div class="3u">
                        
                            <!-- Links -->
                                <section class="widget-links">
                                   <h2>Depoimentos</h2>
                                    <ul class="style2">
                                        {% if testimonial %}
                                            {% for t in testimonial %}
                                                <li><a href="#">{{ t.message|truncatewords:3 }}</a></li>
                                            {% endfor %}
                                        {% else %}
                                            <li>Nenhum depoimento ainda, tem algo a dizer? <a href="{% url 'home:createtestimonial' %}">Envie o seu agora</a>.</li>
                                        {% endif %}
                                    </ul>
                                    <footer>
                                        <span class="home-test"><a href="{% url 'home:createtestimonial' %}">Envie o seu depoimento</a></span>
                                    </footer>
                                </section>
                        
                        </div>
                        <div class="3u">
                        
                            <!-- Links -->
                                <section class="widget-links">
                                    <h2>Blog/Notícias</h2>
                                    <ul class="style2">
                                    {% for p in posts %}
                                        <li><a href="{% url 'blog:postdetails' p.id %}">{{ p.title|truncatewords:4 }}</a></li>
                                    {% endfor %}
                                    </ul>
                                    <span class="home-test"><a href="{% url 'blog:listposts' %}">Ver todos os posts</a></span>
                                </section>
                        
                        </div>
                        <div class="3u">
                        
                            <!-- Contact -->
                                <section class="widget-contact last">
                                    <h2>Contato</h2>
                                    <ul>
                                        <li><a href="https://twitter.com/OrgAnjoMeu" target="_blank" class="fa fa-twitter solo"><span>Twitter</span></a></li>
                                        <li><a href="https://www.facebook.com/OrgAnjoMeu" target="_blank" class="fa fa-facebook solo"><span>Facebook</span></a></li>
                                        <li><a href="https://plus.google.com/u/0/118099344388980119403/posts" target="_blank" class="fa fa-google-plus solo"><span>Google+</span></a></li>
                                    </ul>
                                    <p>Quadra P1 Lote 7 - Aroeiras<br />
                                    Teresina, Piauí - 64.011-565<br />
                                    contato@anjomeu.org<br />
                                    +55 (86) 8813-5802</p>
                                </section>
                        
                        </div>
                    </div>
                    <div class="row">
                        <div class="12u">
                            <div id="copyright">
                                &copy; Anjo Meu. Todos os direitos reservados.
                            </div>
                        </div>
                    </div>
                </footer>
            </div>

    <!--
    Google Analytics
    -->
    <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-49235873-2', 'auto');
          ga('send', 'pageview');
    </script>

    </body>
</html>

anjo/core/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div id="banner-wrapper">
    <div class="container">
        <div class="row">
            <div class="12u">
            
                <!-- Banner -->
                    <div id="banner" class="box">

                        <div>
                            <div class="row">
                                <div class="7u">
                                    <h2>AnjoMeu.org</h2>
                                    <p>Plataforma de Financiamento coletivo, crie uma campanha ou ajude quem precisa.</p>
                                </div>
                                <div class="5u">
                                    <ul>
                                        <li><a href="{% url 'home:newuser' %}" class="button big fa fa-arrow-circle-right">Criar campanha</a></li>
                                        <li><a href="#content" class="button alt big fa fa-question-circle">Saiba mais</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    
                    </div>

            </div>
        </div>
    </div>
</div>

<!-- Features Wrapper -->
<div id="features-wrapper">
    <div class="container">
        <div class="main">
            <div class="row">
                {% if campaign %}
                    {% for c in campaign %}
                        <div class="arrumada">
                            <div class="4u">
                                    <!-- Box -->
                                    <section class="box box-feature">
                                        <a href="#" class="image image-full"><img src="{{ c.image.url }}" alt="" width="218" height="160" /></a>
                                        <div class="inner">
                                            <header>
                                                <h2>{{ c.title }}</h2>
                                                <span class="byline">Criada por {{ c.user.first_name }} e precisa de R$ {{ c.goal }}</span>
                                            </header>
                                            <p>{{ c.message|truncatewords:10 }}</p>
                                            
                                            <!-- INICIO FORMULARIO BOTAO PAGSEGURO -->
                                            <!-- Declaração do formulário -->  
                                            <form target="pagseguro" method="post"   
                                                action="https://pagseguro.uol.com.br/v2/checkout/cart.html?action=add" accept-charset="ISO-8859-1" class="form-pgs">  
                                                  
                                                <!-- Campos obrigatórios -->  
                                                <input type="hidden" name="receiverEmail" value="fandrefh@gmail.com">  
                                                <input type="hidden" name="currency" value="BRL">  
                                                  
                                                <!-- Itens do pagamento (ao menos um item é obrigatório) -->  
                                                <input type="hidden" name="itemId" value="{{ c.id }}">  
                                                <input type="hidden" name="itemDescription" value="{{ c.title }}">  
                                                <input type="hidden" name="itemAmount" value="{{ c.donations|cut:"," }}">  
                                                <input type="hidden" name="itemQuantity" value="1">  
                                                <input type="hidden" name="itemWeight" value="0"> 
                                                  
                                                <!-- submit do form (obrigatório) -->  
                                                <input type="submit" name="submit" class="button-pgs" value="Quero doar">  
                                                  
                                            </form>
                                            <!-- FINAL FORMULARIO BOTAO PAGSEGURO -->
                                            <a href="{% url 'campaign:campaigndetails' c.id %}" class="details">Ver campanha</a>
                                        </div>
                                    </section>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>Ops! Nenhuma campanha foi encontrada. Aproveite e <a href="{% url 'campaign:createcampaign' %}">crie a sua</a> e comece a arrecadar aquela grana de que tanto precisa!</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<!-- Main Wrapper -->
<div id="main-wrapper">
    <div class="container">
        <div class="row">
            <div class="4u">
            
                <!-- Sidebar -->
                    <div id="sidebar">
                        <section class="widget-thumbnails">
                            <h3>Campanhas criadas</h3>
                            <div class="grid">
                                <div class="row no-collapse half">
                                    {% if camp_created %}
                                        {% for cc in camp_created %}
                                        <div class="6u"><a href="{{ cc.id }}" class="image image-full"><img src="{{ cc.image.url }}" width="180px" height="101" alt="{{ cc.title }}" title="{{ cc.title }}" /></a></div>
                                        {% endfor %}
                                    {% else %}
                                        <p>Ops! Nenhuma campanha foi encontrada. Aproveite e <a href="{% url 'campaign:createcampaign' %}">crie a sua</a> e comece a arrecadar aquela grana de que tanto precisa!</p>
                                    {% endif %}

                                </div>
                            </div>
                            <a href="{% url 'campaign:listcampaign' %}" class="button fa fa-file-text-o">Ver mais</a>
                        </section>
                    </div>
            
            </div>
            <div class="8u">

                <!-- Content -->
                    <div id="content">
                        <section class="last">
                            <h2>Quem somos?</h2>

                            <p>
                                Somos uma plataforma de <a href="http://pt.wikipedia.org/wiki/Financiamento_coletivo" target="_blank" title="Ir para Wikipedia e ver uma descrição">Crowdfunding</a>, em português significa Financiamento coletivo, destina-se através de doações a arrecadar dinheiro online para a realização de projetos pessoais de qualquer natureza.
                            </p>
                            <p>
                                Se precisar crie sua campanha ou faça sua doação!
                            </p>
                            <a href="{% url 'home:newuser' %}" class="button fa fa-arrow-circle-right">Criar campanha</a>
                            <a href="{% url 'campaign:listcampaign' %}" class="button fa fa-arrow-circle-right">Fazer uma doação</a>
                        </section>
                    </div>

            </div>
        </div>
    </div>
</div>
{% endblock content %}