anjo/campaign/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('anjo.campaign.views',
	url(r'^criar-campanha/$', 'create_campaign', name='createcampaign'),
	url(r'^lista-de-campanhas/$', 'list_campaign', name='listcampaign'),
	url(r'^detalhes-da-campanha/(?P<id>\d+)/$', 'details', name='campaigndetails'),
	url(r'^minhas-campanhas/(?P<user_id>\d+)/$', 'list_my_campaign', name='mylistcampaign'),
	url(r'^recebido-campanha/(?P<campaign_id>\d+)/$', 'received', name='receivedcampaign'),
	url(r'^solicitar-saque/$', 'get_payment', name='getpayment'),
	url(r'^sucesso/$', 'create_campaign', name='succ'),
)

anjo/core/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('anjo.core.views',
	url(r'^$', 'homepage', name='homepage'),
	url(r'^enviar-depoimento/$', 'create_testimonial', name='createtestimonial'),
	url(r'^depoimentos/$', 'testimonial', name='testimonials'),
	url(r'^dados-bancarios/$', 'add_bank', name='addbank'),
	url(r'^quem-somos/$', 'about', name='aboutus'),
	url(r'^como-funciona/$', 'howitwork', name='howwork'),
	url(r'^anjos/$', 'donor', name='donors'),
	url(r'^novo-usuario/$', 'register', name='newuser'),
	url(r'^login/$', 'user_login', name='userlogin'),
	url(r'^usuario-logado/$', 'user_logged', name='userlogged'),
	url(r'^logout/$', 'user_logout', name='userlogout'),
	url(r'^meus-dados/(?P<user_id>\d+)/$', 'user_information', name='userinfor'),
)

anjo/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^campanha/', include('anjo.campaign.urls', namespace='campaign')),
    url(r'^blog/', include('anjo.blog.urls', namespace='blog')),
    # Examples:
    # url(r'^$', 'anjo.views.home', name='home'),
    # url(r'^anjo/', include('anjo.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('anjo.core.urls', namespace='home')),
)

from django.conf import settings
urlpatterns += patterns('django.views.static',
	url(r'^static/(?P<path>.*)$', 'serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', 'serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^js/(?P<path>.*)$', 'serve', {'document_root': 'public/js'}),
)

anjo/core/models.py
#coding: utf-8
from django.db import models
from django.contrib.auth.models import User
from anjo.campaign.models import Campaign

# Create your models here.
class AboutUs(models.Model):
	title = models.CharField(max_length=70)
	about_us = models.TextField()

	def __unicode__(self):
		return self.title

	class Meta:
		verbose_name=u'About Us'
		verbose_name_plural=u'About Us'

class HowItWork(models.Model):
	title = models.CharField(max_length=70)
	how_work = models.TextField()

	def __unicode__(self):
		return self.title

	class Meta:
		verbose_name=u'How it Work'
		verbose_name_plural=u'How it Work'

class UserProfile(models.Model):
	GENDER_CHOICES = (
		('M', 'Masculino'),
		('F', 'Feminino')
	)
	user = models.OneToOneField(User)
	cpf = models.CharField(u'CPF', max_length=14, help_text='Formato: 000.000.000-00')
	birthday = models.DateField(u'Data de Nascimento', help_text='Formato: 00/00/0000')
	gender = models.CharField(u'Sexo', max_length=1, choices=GENDER_CHOICES)
	address = models.CharField(u'Endereço', max_length=100, help_text='Informe seu endereço completo')
	code_postal = models.CharField(u'CEP', max_length=10, help_text='Formato: 00.000-000')
	neighborhood = models.CharField(u'Bairro', max_length=50)
	state = models.CharField(u'Estado', max_length=2)
	city = models.CharField(u'Cidade', max_length=50)
	phone_number = models.CharField(u'Telefone/Celular', max_length=14, help_text='Formato: (00)00000-0000')
	created_at = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.user.username

class Testimonials(models.Model):
	name = models.CharField(u'Nome', max_length=30)
	message = models.TextField(u'Mensagem')
	active = models.BooleanField(default=False)
	created_at = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.name

class Banks(models.Model):
	code_bank = models.PositiveIntegerField(u'Número do Banco', blank=True, null=True)
	bank_name = models.CharField(u'Nome do Banco', max_length=70)

	def __unicode__(self):
		return self.bank_name

	class Meta:
		verbose_name=u'Bank'
		verbose_name_plural=u'Banks'

class UserBank(models.Model):
	user = models.ForeignKey(User, blank=True, null=True, verbose_name=u'Usuário')
	bank = models.ForeignKey('Banks', verbose_name=u'Banco', unique=True)
	agency = models.CharField(u'Agência', max_length=20, unique=True)
	account_bank = models.CharField(u'Conta Bancária', max_length=50, unique=True)
	operation = models.CharField(u'Operação', max_length=10, blank=True, null=True, unique=True, help_text='Para correntista da CEF')

	def __unicode__(self):
		return "%s, %s, %s" % (self.bank, self.agency, self.account_bank)

	class Meta:
		verbose_name=u'User Bank'
		verbose_name_plural=u'User\'s Bank'

class DashUser(models.Model):
	campaign = models.ForeignKey(Campaign)
	name_donator = models.CharField(max_length=100, blank=True)
	email_donator = models.EmailField(blank=True)
	value = models.DecimalField(max_digits=15, decimal_places=2)

	def __unicode__(self):
		return "%s - %s - %d" % (self.name_donator, self.email_donator, self.value)

anjo/core/forms.py
#coding: utf-8
from django import forms
from localflavor.br.br_states import STATE_CHOICES
from django.contrib.auth.models import User
from .models import UserProfile, Testimonials, UserBank, Banks


class TestimonialsForm(forms.ModelForm):
	class Meta:
		model = Testimonials
		exclude = ('active',)

class UserForm(forms.ModelForm):
	first_name = forms.CharField(label='Nome')
	last_name = forms.CharField(label='Sobrenome')
	username = forms.CharField(label='Nome de usuário')
	email = forms.EmailField(label='E-mail')
	password = forms.CharField(label='Senha', widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ('first_name', 'last_name', 'username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
	state = forms.ChoiceField(label='Estado', choices=STATE_CHOICES)

	class Meta:
		model = UserProfile
		fields = ('cpf', 'birthday', 'gender', 'address', 'code_postal', 'neighborhood', 'state', 'city', 'phone_number')

class BanksForm(forms.ModelForm):
	class Meta:
		model = Banks
		excludes = ('code_bank')

class UserBankForm(forms.ModelForm):
	class Meta:
		model = UserBank
		excludes = ('user')

anjo/core/views.py
# coding: utf-8
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect

from .models import UserProfile, UserBank

from .models import AboutUs, HowItWork, Testimonials
from anjo.campaign.models import Campaign
from anjo.blog.models import Post
from .forms import UserForm, UserProfileForm, TestimonialsForm, UserBankForm, BanksForm

def homepage(request):
	campaign = Campaign.objects.all().order_by('-created_at')[:5]
	camp_created = Campaign.objects.all().order_by('-created_at')[:4]
	return render(request, 'index.html', {'campaign': campaign, 'camp_created': camp_created})

def about(request):
	about_us = AboutUs.objects.all()
	return render(request, 'core/about_us.html', {'about_us': about_us})

def howitwork(request):
	how_work = HowItWork.objects.all()
	return render(request, 'core/how_it_work.html', {'how_work': how_work})

def donor(request):
	return render(request, 'core/donors.html')

def register(request):

	registered = False

	if request.method == 'POST':
		user_form = UserForm(data=request.POST)
		profile_form = UserProfileForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():

			user = user_form.save()

			user.set_password(user.password)
			user.save()

			profile = profile_form.save(commit=False)
			profile.user = user

			profile.save()

			registered = True

		else:
			print user_form.errors, profile_form.errors
	
	else:
		user_form = UserForm()
		profile_form = UserProfileForm()

	return render(request, 'core/register_user.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

def user_login(request):

	if request.method == 'POST':

		username = request.POST['username']
		password = request.POST['password']

		user = authenticate(username=username, password=password)

		if user is not None:

			if user.is_active:
				login(request, user)
				return HttpResponseRedirect('/usuario-logado/')
			else:
				return HttpResponse('Sua conta está desabilitada.')
		else:
			print('Login inválido, detalhes: {0}, {1}'.format(username, password))
			login_error = 'Ops! Alguma coisa que "não está certo" deu errado! Por favor, tente novamente. :)'
			return render(request, 'core/user_login.html', {'login_error': login_error})

	else:
		return render(request, 'core/user_login.html', {})

@login_required
def user_logged(request):
	return render(request, 'core/user_logged.html')

@login_required
def user_logout(request):
	logout(request)
	return HttpResponseRedirect('/')

def create_testimonial(request):
	created = False
	
	if request.method == 'POST':
		test_form = TestimonialsForm(data=request.POST)
		if test_form.is_valid():
			test_form.save()
			created = True
	else:
		test_form = TestimonialsForm()
	return render(request, 'core/create_testimonial.html', {'test_form': test_form, 'created': created})



def testimonial(request):
	testimonial = Testimonials.objects.all().order_by('-created_at')
	return render(request, 'core/testimonials.html', {'testimonial': testimonial})


@login_required
def add_bank(request):
	created = False
	if request.method == 'POST':
		bank_form = UserBankForm(request.POST)
		if bank_form.is_valid():
			bf = bank_form.save(commit=False)
			bf.user = request.user
			bf.save()
			created = True
		else:
			print(bank_form.errors)
	else:
		bank_form = UserBankForm()
	return render(request, 'core/user_bank.html', {'bank_form': bank_form, 'created': created})

@login_required
def user_information(request, user_id):
	user_infor = get_object_or_404(UserProfile, user=user_id)
	user_bank = get_object_or_404(UserBank, user=user_id)
	return render(request, 'core/user_information.html', {'user_infor': user_infor, 'user_bank': user_bank})

anjo/core/templates/core/about_us.html
{% extends 'base.html' %}

{% block title %}Quem somos | {{ block.super }}{% endblock title %}

{% block content %}

	<div class="container">
		{% for a in about_us %}
			<h3>{{ a.title }}</h3>
			{{ a.about_us|safe }}
		{% endfor %}
	</div>
{% endblock content %}

anjo/core/templates/core/create_testimonial.html
{% extends 'base.html' %}

{% block title %}Envie seu depoimento | {{ block.super }}{% endblock title %}

{% block content %}
	<div class="container">
		<h4>Tem algo a dizer sobre o AnjoMeu.org? Aproveite, envie elogios, agradecimentos, críticas, precisamos da sua opinião.</h4>
		{% if created %}
			<p>Obrigado! Seu comentário foi enviado com sucesso, seu feedback é muito para nós! :D</p>
		{% else %}
			<form method="POST" action="{% url 'home:createtestimonial' %}">
				{% csrf_token %}
				<div class="field">
					<p class="field-label">{{ test_form.name.label }}</p>
					<p class="field-input">{{ test_form.name }}</p>
					<p class="hint">
						Digite seu nome.
						{{ test_form.name.help_text }}
					</p>
					<ul class="message-error">
						<li>{{ test_form.name.errors }}</li>
					</ul>
				</div>
				<div class="field">
					<p class="field-label">{{ test_form.message.label }}</p>
					<p class="field-input">{{ test_form.message }}</p>
					<p class="hint">
						Digite sua mensagem.
						{{ test_form.message.help_text }}
					</p>
					<ul class="message-error">
						<li>{{ test_form.message.errors }}</li>
					</ul>
				</div>
				<input type="submit" value="Enviar depoimento" class="submit-form">
			</form>
		{% endif %}
	</div>
{% endblock content %}

anjo/core/templates/core/donors.html
{% extends 'base.html' %}

{% block title %}Quem fez doações | {{ block.super }}{% endblock title %}

{% block content %}
	<div class="container">
		<h3>Anjos de bom coração que apoiam nossa iniciativa. Obrigado!!!</h3>
		<div class="fb-like-box" data-href="https://www.facebook.com/OrgAnjoMeu" data-width="1000" data-height="210" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="false" data-show-border="true"></div>
	</div>
{% endblock content %}

anjo/core/templates/core/how_it_work.html
{% extends 'base.html' %}

{% block title %}Como funciona | {{ block.super }}{% endblock title %}


{% block content %}
	<div class="container">
		{% for c in how_work %}
			<h3>{{ c.title }}</h3>
			{{ c.how_work|safe }}
		{% endfor %}
	</div>
{% endblock content %}

anjo/core/templates/core/register_user.html
{% extends 'base.html' %}

{% block title %}Cadastro de usuário | {{ block.super }}{% endblock title %}

{% block content %}
	<div class="container">
		{% if user.is_authenticated %}
			<p>Ops! Você já está cadastrado e Logado! Aproveite para <a href="{% url 'campaign:createcampaign' %}">criar uma campanha</a> ou <a href="{% url 'campaign:listcampaign' %}">fazer uma doação</a>. ;)</p>
		{% else %}
			{% if registered %}
				Obrigado por se cadastrar, faça <a href="{% url 'home:userlogin' %}">Login</a> e Crie uma campanha ou Faça uma <a href="#">doação!</a>
			{% else %}
			<div id="add-user">
				<h3>Já faz parte da nossa comunidade? Então faça <a href="{% url 'home:userlogin' %}">Login</a> senão, preencha os campos abaixo e contribua para um mundo melhor.</h3>
				<form method="POST", action="{% url 'home:newuser' %}">
						{% csrf_token %}
						
						<div class="field">
							<p class="field-label">{{ user_form.first_name.label }}</p>
							<p class="field-input">{{ user_form.first_name }}</p>
							<p class="hint">
								Digite seu nome.
								{{ user_form.first_name.help_text }}
							</p>
							<ul class="message-error">
								<li>{{ user_form.first_name.errors }}</li>
							</ul>
						</div>
						<div class="field">
							<p class="field-label">{{ user_form.last_name.label }}</p>
							<p class="field-input">{{ user_form.last_name }}</p>
							<p class="hint">
								Digite seu sobrenome.
								{{ user_form.last_name.help_text }}
							</p>
							<ul class="message-error">
								<li>{{ user_form.last_name.errors }}</li>
							</ul>
						</div>
						<div class="field">
							<p class="field-label">{{ user_form.email.label }}</p>
							<p class="field-input">{{ user_form.email }}</p>
							<p class="hint">
								Informe seu e-mail.
								{{ user_form.email.help_text }}
							</p>
							<ul class="message-error">
								<li>{{ user_form.email.errors }}</li>
							</ul>
						</div>
						<div class="field">
							<p class="field-label">{{ user_form.username.label }}</p>
							<p class="field-input">{{ user_form.username }}</p>
							<p class="hint">
								Digite um nome de usuário.
								{{ user_form.username.help_text }}
							</p>
							<ul class="message-error">
								<li>{{ user_form.username.errors }}</li>
							</ul>
						</div>
						<div class="field">
							<p class="field-label">{{ user_form.password.label }}</p>
							<p class="field-input">{{ user_form.password }}</p>
							<p class="hint">
								Digite uma senha.
								{{ user_form.password.help_text }}
							</p>
							<ul class="message-error">
								<li>{{ user_form.password.errors }}</li>
							</ul>
						</div>
						<div class="field">
							<p class="field-label">{{ profile_form.cpf.label }}</p>
							<p class="field-input">{{ profile_form.cpf }}</p>
							<p class="hint">
								Digite seu CPF.
								{{ profile_form.cpf.help_text }}
							</p>
							<ul class="message-error">
								<li>{{ profile_form.cpf.errors }}</li>
							</ul>
						</div>
						<div class="field">
							<p class="field-label">{{ profile_form.birthday.label }}</p>
							<p class="field-input">{{ profile_form.birthday }}</p>
							<p class="hint">
								Digite sua data de nascimento.
								{{ profile_form.birthday.help_text }}
							</p>
							<ul class="message-error">
								<li>{{ profile_form.birthday.errors }}</li>
							</ul>
						</div>
						<div class="field">
							<p class="field-label">{{ profile_form.gender.label }}</p>
							<p class="field-input">{{ profile_form.gender }}</p>
							<p class="hint">
								Escolha uma opção.
								{{ profile_form.gender.help_text }}
							</p>
							<ul class="message-error">
								<li>{{ profile_form.gender.errors }}</li>
							</ul>
						</div>
						<div class="field">
							<p class="field-label">{{ profile_form.address.label }}</p>
							<p class="field-input">{{ profile_form.address }}</p>
							<p class="hint">
								Digite seu endereço completo.
								{{ profile_form.address.help_text }}
							</p>
							<ul class="message-error">
								<li>{{ profile_form.address.errors }}</li>
							</ul>
						</div>
						<div class="field">
							<p class="field-label">{{ profile_form.code_postal.label }}</p>
							<p class="field-input">{{ profile_form.code_postal }}</p>
							<p class="hint">
								Informe seu CEP.
								{{ profile_form.code_postal.help_text }}
							</p>
							<ul class="message-error">
								<li>{{ profile_form.code_postal.errors }}</li>
							</ul>
						</div>
						<div class="field">
							<p class="field-label">{{ profile_form.neighborhood.label }}</p>
							<p class="field-input">{{ profile_form.neighborhood }}</p>
							<p class="hint">
								Informe seu bairro.
								{{ profile_form.neighborhood.help_text }}
							</p>
							<ul class="message-error">
								<li>{{ profile_form.neighborhood.errors }}</li>
							</ul>
						</div>
						<div class="field">
							<p class="field-label">{{ profile_form.state.label }}</p>
							<p class="field-input">{{ profile_form.state }}</p>
							<p class="hint">
								Escolha um estado.
								{{ profile_form.state.help_text }}
							</p>
							<ul class="message-error">
								<li>{{ profile_form.state.errors }}</li>
							</ul>
						</div>
						<div class="field">
							<p class="field-label">{{ profile_form.city.label }}</p>
							<p class="field-input">{{ profile_form.city }}</p>
							<p class="hint">
								Informe sua cidade.
								{{ profile_form.city.help_text }}
							</p>
							<ul class="message-error">
								<li>{{ profile_form.city.errors }}</li>
							</ul>
						</div>
						<div class="field">
							<p class="field-label">{{ profile_form.phone_number.label }}</p>
							<p class="field-input">{{ profile_form.phone_number }}</p>
							<p class="hint">
								Informe um número de telefone para contato.
								{{ profile_form.phone_number.help_text }}
							</p>
							<ul class="message-error">
								<li>{{ profile_form.phone_number.errors }}</li>
							</ul>
						</div>
						<input type="submit" value="Cadastrar" class="submit-form">
				</form>
			</div>
			{% endif %}
		{% endif %}
	</div>
{% endblock content %}

anjo/core/templates/core/testimonials.html
{% extends 'base.html' %}

{% block title %}Depoimentos | {{ block.super }}{% endblock title %}

{% block content %}
	<div class="container">
		<h3>Saiba o que estão falando do AnjoMeu.org!</h3>
		{% if testimonial %}
		{% for t in testimonial %}
		<blockquote>
				<h5>{{ t.name }}</h5>
				<p>
					<cite>{{ t.message }}</cite>
				</p>
		</blockquote>
		{% endfor %}
		{% else %}
		<p>Nenhum depoimento ainda, tem algo a dizer? <a href="{% url 'home:createtestimonial' %}">Envie o seu agora</a>.</p>
		{% endif %}
	</div>
{% endblock content %}

anjo/core/templates/core/user_bank.html
{% extends 'base.html' %}

{% block title %}Informações bancárias | {{ block.super }}{% endblock title %}

{% block content %}
	<div class="container">
			<div id="add-user">
			{% if created %}
			<p class="account-success">Conta cadastrada com sucesso!</p>
			{% else %}
				<h3>Informe seus dados bancários</h3>
				<form method="POST", action="{% url 'home:addbank' %}">
						{% csrf_token %}
						
						<div class="field">
							<p class="field-label">{{ bank_form.bank.label }}</p>
							<p class="field-input">{{ bank_form.bank }}</p>
							<p class="hint">
								Informe o banco.
								{{ bank_form.agency.help_text }}
							</p>
							<ul class="message-error">
								<li>{{ bank_form.agency.errors }}</li>
							</ul>
						</div>
						<div class="field">
							<p class="field-label">{{ bank_form.agency.label }}</p>
							<p class="field-input">{{ bank_form.agency }}</p>
							<p class="hint">
								Informe o número da agência.
								{{ bank_form.agency.help_text }}
							</p>
							<ul class="message-error">
								<li>{{ bank_form.agency.errors }}</li>
							</ul>
						</div>
						<div class="field">
							<p class="field-label">{{ bank_form.account_bank.label }}</p>
							<p class="field-input">{{ bank_form.account_bank }}</p>
							<p class="hint">
								Informe o número da sua conta bancária.
								{{ bank_form.account_bank.help_text }}
							</p>
							<ul class="message-error">
								<li>{{ bank_form.account_bank.errors }}</li>
							</ul>
						</div>
						<div class="field">
							<p class="field-label">{{ bank_form.operation.label }}</p>
							<p class="field-input">{{ bank_form.operation }}</p>
							<p class="hint">
								Informe a operação, caso exista.
								{{ bank_form.operation.help_text }}
							</p>
							<ul class="message-error">
								<li>{{ bank_form.operation.errors }}</li>
							</ul>
						</div>
						<input type="submit" value="Cadastrar" class="submit-form">
				</form>
			</div>
			{% endif %}
	</div>
{% endblock content %}

anjo/core/templates/core/user_information.html
{% extends 'base.html' %}

{% block title %}Informações do usuário | {{ block.super }}{% endblock title %}

{% block content %}
	<div class="container">
		{% if user.is_authenticated %}
				<h3>Meus dados</h3>
				<div class="infor-user">
					<table summary="Informações pessoais" class="table">
					<caption>Informações pessoais</caption>
						<thead>
							<tr>
								<th>Nome</th>
								<th>Sobrenome</th>
								<th>CPF</th>
								<th>Endereço</th>
								<th>Cidade</th>
								<th>Estado</th>
							</tr>
						</thead>
						<tbody style="text-align: center;">
							<tr>
								<th>{{ user_infor.user.first_name }}</th>
								<th>{{ user_infor.user.last_name }}</th>
								<th>{{ user_infor.cpf }}</th>
								<th>{{ user_infor.address }}</th>
								<th>{{ user_infor.city }}</th>
								<th>{{ user_infor.state }}</th>
							</tr>
						</tbody>
					</table>
					<table summary="Informações bancárias" class="table">
					<caption>Informações bancárias</caption>
						<thead>
							<tr>
								<th>Cód. Banco</th>
								<th>Nome do Banco</th>
								<th>Agência</th>
								<th>Conta</th>
								<th>Operação</th>
							</tr>
						</thead>
						<tbody style="text-align: center;">
							<tr>
								<th>{{ user_bank.bank.code_bank }}</th>
								<th>{{ user_bank.bank }}</th>
								<th>{{ user_bank.agency }}</th>
								<th>{{ user_bank.account_bank }}</th>
								<th>{{ user_bank.operation }}</th>
							</tr>
						</tbody>
					</table>
				</div>
		{% endif %}
{% endblock content %}

anjo/core/templates/core/user_logged.html
{% extends 'base.html' %}

{% block title %}Usuário logado | {{ block.super }}{% endblock title %}

{% block content %}
	<div class="container">
		{% if user.is_authenticated %}
			<h2>Login efetuado com sucesso!</h2>
				<h3>Comece aqui</h3>
				<div class="infor-user">
					<ul class="menu-user">
						<li><a href="{% url 'home:userinfor' user.id %}" class="link-logged">Meus dados</a></li>
						<li><a href="{% url 'campaign:createcampaign' %}" class="link-logged">Crie sua campanha</a><li><a href="{% url 'campaign:mylistcampaign' user.id %}" class="link-logged">Ver minhas campanhas</a></li><li><a href="{% url 'campaign:createcampaign' %}" class="link-logged">Crie sua campanha</a></li>
						<li><a href="{% url 'campaign:listcampaign' %}" class="link-logged">Faça uma doação</a></li>
						<li><a href="{% url 'home:addbank' %}" class="link-logged">Cadastre seus dados financeiros (necessário para o recebimento das doações)</a></li>
						<li><a href="{% url 'campaign:getpayment' %}" class="link-logged">Solicitar saque</a></li>
					</ul>
				</div>
		{% endif %}
{% endblock content %}

anjo/core/templates/core/user_login.html
{% extends 'base.html' %}

{% block title %}Login de usuário | {{ block.super }}{% endblock title %}

{% block content %}
	<div class="container">
		<div id="form-login" class="form-login">
			<ul class="message-error">
				{% if login_error %}
					<li>{{ login_error }}</li>
				{% endif %}
			</ul>
			<form method="POST", action="{% url 'home:userlogin' %}">
					{% csrf_token %}
					<div class="field">
						<p class="field-label">Usuário</p>
						<input type="text" name="username" placeholder="Digite seu nome de usuário" required>
						<p class="field-label">Senha</p>
						<input type="password" name="password" placeholder="Digite sua senha" required>
					</div>
					<input type="submit" value="Entrar" class="submit-form"> <span><a href="{% url 'home:newuser' %}">Primeira vez? Cadastre-se aqui.</a></span>
			</form>
		</div>
	</div>
{% endblock content %}