anjo/campaign/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('anjo.campaign.views',
	url(r'^criar-campanha/$', 'create_campaign', name='createcampaign'),
	url(r'^lista-de-campanhas/$', 'list_campaign', name='listcampaign'),
	url(r'^detalhes-da-campanha/(?P<id>\d+)/$', 'details', name='campaigndetails'),
	url(r'^minhas-campanhas/(?P<user_id>\d+)/$', 'list_my_campaign', name='mylistcampaign'),
	url(r'^recebido-campanha/(?P<campaign_id>\d+)/$', 'received', name='receivedcampaign'),
	url(r'^solicitar-saque/$', 'get_payment', name='getpayment'),
	url(r'^sucesso/$', 'create_campaign', name='succ'),
)

anjo/core/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('anjo.core.views',
	url(r'^$', 'homepage', name='homepage'),
	url(r'^enviar-depoimento/$', 'create_testimonial', name='createtestimonial'),
	url(r'^depoimentos/$', 'testimonial', name='testimonials'),
	url(r'^dados-bancarios/$', 'add_bank', name='addbank'),
	url(r'^quem-somos/$', 'about', name='aboutus'),
	url(r'^como-funciona/$', 'howitwork', name='howwork'),
	url(r'^anjos/$', 'donor', name='donors'),
	url(r'^novo-usuario/$', 'register', name='newuser'),
	url(r'^login/$', 'user_login', name='userlogin'),
	url(r'^usuario-logado/$', 'user_logged', name='userlogged'),
	url(r'^logout/$', 'user_logout', name='userlogout'),
	url(r'^meus-dados/(?P<user_id>\d+)/$', 'user_information', name='userinfor'),
)

anjo/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^campanha/', include('anjo.campaign.urls', namespace='campaign')),
    url(r'^blog/', include('anjo.blog.urls', namespace='blog')),
    # Examples:
    # url(r'^$', 'anjo.views.home', name='home'),
    # url(r'^anjo/', include('anjo.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('anjo.core.urls', namespace='home')),
)

from django.conf import settings
urlpatterns += patterns('django.views.static',
	url(r'^static/(?P<path>.*)$', 'serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', 'serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^js/(?P<path>.*)$', 'serve', {'document_root': 'public/js'}),
)

anjo/campaign/models.py
# coding:utf-8
from django.db import models
from django.contrib.auth.models import User
from locale import setlocale, currency as coin, LC_ALL
import uuid, os

# Create your models here.

class Campaign(models.Model):

	def generate_new_filename(instance, filename):
		ext = filename.split('.')[-1]
		filename = '%s.%s' % (uuid.uuid4(), ext)
		return os.path.join('images', filename)


	user = models.ForeignKey(User, blank=True, null=True)
	title = models.CharField(u'Título da sua Campanha', max_length=50)
	goal = models.DecimalField(u'Meta R$', max_digits=15, decimal_places=2, help_text='De quanto você precisa?')
	donations = models.DecimalField(u'Doação de R$', max_digits=5, decimal_places=2, help_text='A partir de quanto gostaria de receber.');
	image = models.ImageField(u'Envie uma imagem', upload_to=generate_new_filename, help_text='Envie uma bela imagem para sua campanha.')
	message = models.TextField(u'Fale sobre sua campanha', help_text='Faça uma boa descrição da sua campanha')
	created_at = models.DateTimeField(auto_now_add=True)

	def real_coin(self):
		setlocale(LC_ALL, 'pt_BR.UTF-8')
		return coin(self.goal, grouping=True)
	real_coin.short_description = 'Meta: '

	def __unicode__(self):
		return self.title

class GetPayment(models.Model):
	campaign_c = models.ForeignKey(Campaign, verbose_name=u'Campanha', blank=True, null=True)
	user_c = models.ForeignKey(User, verbose_name=u'Usuário', blank=True, null=True)
	value = models.DecimalField(u'Valor R$', max_digits=15, decimal_places=2, help_text='Quanto quer sacar?')
	request_date = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.campaign

anjo/campaign/forms.py
from django import forms
from .models import Campaign, GetPayment

class GetPaymentForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		super(GetPaymentForm, self).__init__(*args, **kwargs)
		self.fields['value'].localize = True
		self.fields['value'].widget.is_localized = True

	class Meta:
		model = GetPayment

class CampaignForm(forms.ModelForm):

	def __init__(self, *args, **kwargs):
		super(CampaignForm, self).__init__(*args, **kwargs)
		self.fields['goal'].localize = True
		self.fields['goal'].widget.is_localized = True
		self.fields['donations'].localize = True
		self.fields['donations'].widget.is_localized = True

	class Meta:
		model = Campaign

anjo/campaign/views.py
# coding: utf-8
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.db.models import Sum

from .models import Campaign, GetPayment
from .forms import CampaignForm, GetPaymentForm

from anjo.core.models import DashUser

@login_required
def create_campaign(request):
	if request.method == 'POST':
		campaign_form = CampaignForm(request.POST, request.FILES)
		if campaign_form.is_valid():
			cf = campaign_form.save(commit=False)
			cf.user = request.user
			cf.save()
			model = cf
			return render(request, 'campaign/success.html', {'model': model})
		else:
			print(campaign_form.errors)
	else:
		campaign_form = CampaignForm()
	return render(request, 'campaign/create_campaign.html', {'campaign_form': campaign_form})

def list_campaign(request):
	list_camp = Campaign.objects.all().order_by('-created_at')
	paginator = Paginator(list_camp, 5)
	page = request.GET.get('page')
	try:
		list_campaign = paginator.page(page)
	except PageNotAnInteger:
		list_campaign = paginator.page(1)
	except EmptyPage:
		list_campaign = paginator.page(paginator.num_pages)
	return render(request, 'campaign/list_campaign.html', {'list_campaign': list_campaign})

def details(request, id):
	camp_destails = get_object_or_404(Campaign, id=id)
	return render(request, 'campaign/list_campaign_detais.html', {'camp_destails': camp_destails})

@login_required
def list_my_campaign(request, user_id):
	my_campaign = Campaign.objects.filter(user=user_id)
	paginator = Paginator(my_campaign, 5)
	page = request.GET.get('page')
	try:
		mycampaign = paginator.page(page)
	except PageNotAnInteger:
		mycampaign = paginator.page(1)
	except EmptyPage:
		mycampaign = paginator.page(paginator.num_pages)
	return render(request, 'campaign/list_my_campaign.html', {'mycampaign': mycampaign})

@login_required
def received(request, campaign_id):
	total_campaign = DashUser.objects.filter(campaign=campaign_id).aggregate(Sum('value'))
	rec_campaign = DashUser.objects.filter(campaign=campaign_id)
	return render(request, 'campaign/received_campaign.html', {'rec_campaign': rec_campaign, 'total_campaign': total_campaign})

@login_required
def get_payment(request):
	campaign_p = Campaign.objects.filter(user=request.user)
	# c_id = request.POST.get('optid')
	# camp = Campaign.objects.get(id=request.POST.get('optid'))
	# print(c_id)
	created = False
	if request.method == 'POST':
		camp = Campaign.objects.get(id=request.POST.get('optid'))
		pay_form = GetPaymentForm(request.POST)
		if pay_form.is_valid():
			pf = pay_form.save(commit=False)
			pf.campaign_c = camp
			pf.user_c = request.user
			pf.save()
			created = True
		else:
			print(pay_form.errors)
	else:
		pay_form = GetPaymentForm()
	return render(request, 'campaign/get_payment.html', {'pay_form': pay_form, 'created': created, 'campaign_p': campaign_p})

anjo/campaign/templates/campaign/create_campaign.html
{% extends 'base.html' %}

{% block title %}Criar minha campanha | {{ block.super }}{% endblock title %}

{% block content %}
	<div class="container">
		<div id="create-campaign">
			<h3>Preencha os campos abaixo para criar sua campanha.</h3>
			<form method="POST", enctype="multipart/form-data" action="{% url 'campaign:createcampaign' %}">
					{% csrf_token %}
					
					<div class="field">
						<p class="field-label">{{ campaign_form.title.label }}</p>
						<p class="field-input">{{ campaign_form.title }}</p>
						<p class="hint">
							Digite um título para sua campanha.
							{{ campaign_form.title.help_text }}
						</p>
						<ul class="message-error">
							<li>{{ campaign_form.title.errors }}</li>
						</ul>
					</div>
					<div class="field">
						<p class="field-label">{{ campaign_form.goal.label }}</p>
						<p class="field-input">{{ campaign_form.goal }}</p>
						<p class="hint">
							Digite o valor da sua meta.
							{{ campaign_form.goal.help_text }}
						</p>
						<ul class="message-error">
							<li>{{ campaign_form.goal.errors }}</li>
						</ul>
					</div>
					<div class="field">
						<p class="field-label">{{ campaign_form.donations.label }}</p>
						<p class="field-input">{{ campaign_form.donations }}</p>
						<p class="hint">
							A partir de quanto gostaria de receber?
							{{ campaign_form.donations.help_text }}
						</p>
						<ul class="message-error">
							<li>{{ campaign_form.donations.errors }}</li>
						</ul>
					</div>
					<div class="field">
						<p class="field-label">{{ campaign_form.image.label }}</p>
						<p class="field-input">{{ campaign_form.image }}</p>
						<p class="hint">
							Envie uma imagem que represente sua campanha.
							{{ campaign_form.image.help_text }}
						</p>
						<ul class="message-error">
							<li>{{ campaign_form.image.errors }}</li>
						</ul>
					</div>
					<div class="field">
						<p class="field-label">{{ campaign_form.message.label }}</p>
						<p class="field-input">{{ campaign_form.message }}</p>
						<p class="hint">
							Descreva sua campanha, explique porque você precisa dessa ajuda.
							{{ campaign_form.message.help_text }}
						</p>
						<ul class="message-error">
							<li>{{ campaign_form.message.errors }}</li>
						</ul>
					</div>
					<input type="submit" value="Criar campanha" class="submit-form">
			</form>
		</div>
	</div>
{% endblock content %}

anjo/campaign/templates/campaign/get_payment.html
{% extends 'base.html' %}

{% block title %}Solicitar saque | {{ block.super }}{% endblock title %}

{% block content %}
	<div class="container">
		<h4>Solicitação de saque</h4>
		{% if created %}
			<p>Obrigado! Em breve será depositado na sua conta o valor do saque solicitado.</p>
		{% else %}
			<form method="POST" action="{% url 'campaign:getpayment' %}">
				{% csrf_token %}
				<div class="field">

					<p class="field-label">{{ pay_form.campaign.label }}</p>
					<select name="optid">
					<option>Selecione...</option>
						{% for cp in campaign_p %}
							<option value="{{ cp.id }}">{{ cp.title }}</option>
						{% endfor %}
					</select>
					<p class="hint">
						Escolha uma campanha.
						{{ pay_form.campaign.help_text }}
					</p>
					<ul class="message-error">
						<li>{{ pay_form.campaign.errors }}</li>
					</ul>
				</div>
				<div class="field">
					<p class="field-label">{{ pay_form.value.label }}</p>
					<p class="field-input">{{ pay_form.value }}</p>
					<p class="hint">
						Valor que gostaria de sacar.
						{{ pay_form.value.help_text }}
					</p>
					<ul class="message-error">
						<li>{{ pay_form.value.errors }}</li>
					</ul>
				</div>
				<input type="submit" value="Solicitar" class="submit-form">
			</form>
		{% endif %}
	</div>
{% endblock content %}

anjo/campaign/templates/campaign/list_campaign.html
{% extends 'base.html' %}

{% block title %}Campanhas criadas | {{ block.super }}{% endblock title %}

{% block content %}
	<div class="container">
		{% if list_campaign %}
			<h2>Escolha uma ou mais campanhas e faça uma doação!</h2>
			{% for lc in list_campaign %}
			<section class="lc">
				<div class="lc-img">
					<img src="{{ lc.image.url }}" width="200px" height="120px" alt="{{ lc.title }}" title="{{ lc.title }}">
				</div>
				<h3>{{ lc.title }}</h3>
				<p>{{ lc.message|truncatewords:15 }}</p>
				<span class="lc-camp"><a href="{% url 'campaign:campaigndetails' lc.id %}">Ver campanha...</a></span>
			</section>
			{% endfor %}
		{% else %}
			Não existe nenhuma campanha criada, <a href="{% url 'campaign:createcampaign' %}">crie a sua</a> e consiga aquela grana de que tanto precisa!
		{% endif %}

	<div class="pagination">
    <span class="step-links">
        {% if list_campaign.has_previous %}
            <a href="?page={{ list_campaign.previous_page_number }}">voltar</a>
        {% endif %}

        <span class="current">
            Página {{ list_campaign.number }} de {{ list_campaign.paginator.num_pages }}
        </span>

        {% if list_campaign.has_next %}
            <a href="?page={{ list_campaign.next_page_number }}">próxima</a>
        {% endif %}
    </span>
</div>
	</div>
{% endblock content %}

anjo/campaign/templates/campaign/list_campaign_detais.html
{% extends 'base.html' %}

{% block title %}Detalhes da campanha | {{ block.super }}{% endblock title %}

{% block content %}
	<div class="container">
		{% if camp_destails %}
			<h2>Vai fazer uma doação? Saiba mais!</h2>
			<section class="lc">
				<div class="lc-img-details">
					<img src="{{ camp_destails.image.url }}" width="308px" height="208px" alt="{{ camp_destails.title }}" title="{{ camp_destails.title }}">
				</div>
				<h3>{{ camp_destails.title }}</h3>
				<p>{{ camp_destails.message }}</p>
				<div class="camp-details">
					<p>Data da criação: {{ camp_destails.created_at }}</p>
					<p>Meta R$: {{ camp_destails.goal }}</p>
					<p>Doações a partir de R$: {{ camp_destails.donations }}</p>
					<!-- INICIO FORMULARIO BOTAO PAGSEGURO -->
                    <!-- Declaração do formulário -->  
                    <form target="pagseguro" method="post"   
                        action="https://pagseguro.uol.com.br/v2/checkout/cart.html?action=add" accept-charset="ISO-8859-1" class="form-pgs">  
                          
                        <!-- Campos obrigatórios -->  
                        <input type="hidden" name="receiverEmail" value="fandrefh@gmail.com">  
                        <input type="hidden" name="currency" value="BRL">  
                          
                        <!-- Itens do pagamento (ao menos um item é obrigatório) -->  
                        <input type="hidden" name="itemId" value="{{ camp_destails.id }}">  
                        <input type="hidden" name="itemDescription" value="{{ camp_destails.title }}">  
                        <input type="hidden" name="itemAmount" value="{{ camp_destails.donations|cut:"," }}">  
                        <input type="hidden" name="itemQuantity" value="1">  
                        <input type="hidden" name="itemWeight" value="0"> 
                          
                        <!-- submit do form (obrigatório) -->  
                        <input type="submit" name="submit" class="btn-details" value="Quero doar">  
                          
                    </form>
                    <!-- FINAL FORMULARIO BOTAO PAGSEGURO -->
				</div>
			</section>
		{% else %}
			Desculpe, isso é constragedor, tente acessar a <a href="{% url 'home:homepage' %}">página principal.</a>
		{% endif %}
	</div>
{% endblock content %}

anjo/campaign/templates/campaign/list_my_campaign.html
{% extends 'base.html' %}

{% block title %}Minhas campanhas criadas | {{ block.super }}{% endblock title %}

{% block content %}
	<div class="container">
		{% if mycampaign %}
			<h2>Campanhas criadas por mim</h2>
			{% for mc in mycampaign %}
			<section class="lc">
				<div class="lc-img">
					<img src="{{ mc.image.url }}" width="200px" height="120px" alt="{{ mc.title }}" title="{{ mc.title }}">
				</div>
				<h3>{{ mc.title }}</h3>
				<p>{{ mc.message|truncatewords:15 }}</p>
				<span class="lc-camp"><a href="{% url 'campaign:receivedcampaign' mc.id %}">Ver recebimentos...</a></span>
			</section>
			{% endfor %}
		{% else %}
			Não existe nenhuma campanha criada, <a href="{% url 'campaign:createcampaign' %}">crie a sua</a> e consiga aquela grana de que tanto precisa!
		{% endif %}

	<div class="pagination">
    <span class="step-links">
        {% if mycampaign.has_previous %}
            <a href="?page={{ mycampaign.previous_page_number }}">voltar</a>
        {% endif %}

        <span class="current">
            Página {{ mycampaign.number }} de {{ mycampaign.paginator.num_pages }}
        </span>

        {% if mycampaign.has_next %}
            <a href="?page={{ mycampaign.next_page_number }}">próxima</a>
        {% endif %}
    </span>
</div>
	</div>
{% endblock content %}

anjo/campaign/templates/campaign/received_campaign.html
{% extends 'base.html' %}

{% block title %}Doações recebidas | {{ block.super }}{% endblock title %}

{% block content %}
	<div class="container">
		{% if rec_campaign %}
				<h3>Doações recebidas</h3>
				<div class="infor-user">
					<table summary="Informações pessoais" class="table">
					<caption>Detalhes</caption>
						<thead>
							<tr>
								<th>Cód. Campanha</th>
								<th>Título da Campanha</th>
								<th>Descrição da Campanha</th>
								<th>Nome do Doador</th>
								<th>E-mail do Doador</th>
								<th>Valor Recebido</th>
							</tr>
						</thead>
						<tbody style="text-align: center;">
						{% for rec in rec_campaign %}
							<tr>
								<th>{{ rec.campaign.id }}</th>
								<th>{{ rec.campaign.title }}</th>
								<th>{{ rec.campaign.message }}</th>
								<th>{{ rec.name_donator }}</th>
								<th>{{ rec.email_donator }}</th>
								<th>{{ rec.value }}</th>
							</tr>
						{% endfor %}
						</tbody>
					</table>
					<h4>Total arrecadado até o momento: {{ total_campaign.value__sum }}</h4>
				</div>
		{% else %}
			<p>Nada recebido ainda, mas não desanime, continue compartilhando a sua campanha, com certeza alguém vai doar!</p>
		{% endif %}
{% endblock content %}

anjo/campaign/templates/campaign/success.html
{% extends 'base.html' %}

{% block title %}Campanha criada com sucesso | {{ block.super }}{% endblock title %}

{% block content %}
	<div class="container">
			Obrigado por criar sua campanha com a gente, divulgue o máximo que puder, Facebook, Twitter, fale para os amigos e familiares que você precisa dessa ajuda.
			<section class="fbshare">
				<div class="fb-share-button" data-href="http://anjomeu.org/{% url 'campaign:campaigndetails' model.id %}" data-width="400">
				</div>
			</section>
			<section class="tshare">
				<!-- Twitter Share -->
				<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://anjomeu.org{% url 'campaign:campaigndetails' model.id %}" data-lang="en" data-count="none">Tweet</a>
				<script>
					!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
				</script>
			</section>
			
			
		
	</div>
{% endblock content %}